#ifndef WBSIGNALDETECTWIDGET_GLOBAL_H
#define WBSIGNALDETECTWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WBSIGNALDETECTWIDGET_LIBRARY)
#  define WBSIGNALDETECTWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define WBSIGNALDETECTWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // WBSIGNALDETECTWIDGET_GLOBAL_H
